package com.example.movieappapi.domain.utils

object Url {
    private const val BASE_URL = "https://api.themoviedb.org/3/"
    private const val BASE_IMAGE_URL = "https://image.tmdb.org/t/p/"
    const val REQUEST_TOKEN = "${BASE_URL}authentication/token/new"
    const val LOGIN_USER = "${BASE_URL}authentication/token/validate_with_login"
    const val CREATE_SESSION = "${BASE_URL}authentication/session/new"
    const val GUEST_LOGIN = "${BASE_URL}authentication/guest_session/new"
    const val ACCOUNT_DETAILS = "${BASE_URL}account"
    const val POPULAR_MOVIES = "${BASE_URL}movie/popular"
    const val POPULAR_Tv = "${BASE_URL}tv/popular"
    const val DISCOVER_MOVIES = "${BASE_URL}discover/movie"
    const val DISCOVER_TV = "${BASE_URL}discover/tv"
    const val TOP_RATED_MOVIES = "${BASE_URL}movie/top_rated"
    const val UPCOMING_MOVIES = "${BASE_URL}movie/upcoming"
    const val NOW_PLAYING_MOVIES = "${BASE_URL}movie/now_playing"
    const val SEARCH_ALL = "${BASE_URL}search/multi"
    const val SEARCH_MOVIE = "${BASE_URL}search/movie"
    const val SEARCH_TV = "${BASE_URL}search/tv"
    const val GENRES = "${BASE_URL}genre/movie/list"
    fun getImageUrl(path: String) = "${BASE_IMAGE_URL}original/$path"
    fun getRecommendations(movieId: Int) = "${BASE_URL}movie/$movieId/recommendations"
    fun getSimilarMovies(movieId: Int) = "${BASE_URL}movie/$movieId/similar"
    fun rateMovie(movieId: Int) = "${BASE_URL}/movie/${movieId}/rating"
    fun deleteMovieRating(movieId: Int) = "${BASE_URL}/movie/${movieId}/rating"
    fun rateTv(tvId: Int) = "${BASE_URL}/tv/${tvId}/rating"
    fun deleteTvRating(tvId: Int) = "${BASE_URL}/tv/${tvId}/rating"
    fun getUserLists(accountId: Int) = "${BASE_URL}account/${accountId}/lists"
    fun getUserFavoriteMovies(accountId: Int) = "${BASE_URL}account/${accountId}/favorite/movies"
    fun getUserWatchListMovies(accountId: Int) = "${BASE_URL}account/${accountId}/watchlist/movies"
    fun getUserRatedMovies(accountId: Int) = "${BASE_URL}account/${accountId}/rated/movies"
    fun getUserRatedTv(accountId: Int) = "${BASE_URL}account/${accountId}/rated/tv"
    fun getUserWatchListTv(accountId: Int) = "${BASE_URL}account/${accountId}/watchlist/tv"
    fun getUserRatedTvEpisodes(accountId: Int) = "${BASE_URL}account/${accountId}/rated/tv/episodes"
    fun getUserFavoriteTv(accountId: Int) = "${BASE_URL}account/${accountId}/favorite/tv"
    fun markAsFavorite(accountId: Int) = "${BASE_URL}account/${accountId}/favorite"
    fun addWatchList(accountId: Int) = "${BASE_URL}account/${accountId}/watchlist"
}